import {esc,heading,dialog,toast} from './shared/ui.js';
const label=status=>({configuring:'Интеграция ожидает подключения API',connected:'Подключено',syncing:'Синхронизация',disconnected:'Не подключено',degraded:'Есть ошибки',failed:'Ошибка'}[status]||status);
export async function posPage(api,shop){
 const [p,c]=await Promise.all([api.request('/api/pos/providers'),api.request(`/api/pos/shops/${shop.id}/connections`)]);
 return heading('Настройки → Интеграции → POS')+'<p class="muted">Цена и остаток синхронизируются для выбранного филиала. CSV/Excel остаётся в разделе «Импорт и API».</p><div class="store-grid" style="grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr))">'+p.providers.map(provider=>{
  const connection=c.connections.find(x=>x.provider===provider.code);
  return `<article class="card" style="display:flex;flex-direction:column;gap:8px"><h2>${esc(provider.name)}</h2><p>${esc(connection?label(connection.status):'Интеграция ожидает подключения API')}</p><p>Филиал: ${esc(shop.name)}</p><p>Последний sync: ${esc(connection?.last_sync_at||'—')}</p><p>Товары: ${esc(connection?.products_count||0)} · На проверке: ${esc(connection?.manual_review_count||0)}</p><p>${esc(connection?.last_error_code||'')}</p><div class="actions">${connection?`<button class="button soft" data-pos-detail="${Number(connection.id)}">Статус и настройка</button><button class="button" data-pos-sync="${Number(connection.id)}">Sync</button>${shop.position==='owner'?`<button class="button soft" data-pos-disconnect="${Number(connection.id)}">Отключить</button>`:''}`:shop.position==='owner'?`<button class="button" data-pos-create="${esc(provider.code)}">Настроить</button>`:''}</div>${provider.code==='billz'?'<p><a href="#imports">Настроить официальный BILLZ API</a></p>':''}</article>`;
 }).join('')+'</div>';
}
export function bindPos(api,shop,refresh){
 const base=`/api/pos/shops/${shop.id}/connections`;
 const run=fn=>async e=>{e.preventDefault();const button=e.currentTarget;button.disabled=true;try{await fn();}catch(error){toast(error.message);}finally{button.disabled=false;}};
 document.querySelectorAll('[data-pos-create]').forEach(b=>b.onclick=run(async()=>{await api.request(base,{method:'POST',body:{provider:b.dataset.posCreate}});await refresh();}));
 document.querySelectorAll('[data-pos-sync]').forEach(b=>b.onclick=run(async()=>{const data=await api.request(base+'/'+b.dataset.posSync+'/sync',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:{mode:'incremental'}});toast(data.push_only?'Ожидается передача данных внешним POS adapter':'Sync поставлен в очередь');await refresh();}));
 document.querySelectorAll('[data-pos-disconnect]').forEach(b=>b.onclick=run(async()=>{if(!confirm('Отключить POS? Последние предложения магазина сохранятся.'))return;await api.request(base+'/'+b.dataset.posDisconnect+'/disconnect',{method:'POST',body:{}});await refresh();}));
 document.querySelectorAll('[data-pos-detail]').forEach(b=>b.onclick=run(async()=>{
  const id=Number(b.dataset.posDetail);const provider=b.closest('article').querySelector('h2').textContent;const setup=provider==='EasyTrade'?'Нужны официальная документация EasyTrade API и разрешённый доступ. Интеграция пока не настроена.':provider==='BILLZ'?'Настройте отдельный ключ BILLZ в разделе импорта, пройдите реальную проверку подключения и назначьте каждой POS-точке филиал.':'Universal POS: scoped credential настраивает администратор на backend. Ключ не отображается в кабинете.';const [m,e,h]=await Promise.all(['mappings','errors','history'].map(kind=>api.request(base+'/'+id+'/'+kind)));
  const modal=dialog(`<p>${esc(setup)}</p><p>Требуется подтверждённая внешняя location → физический филиал.</p>${shop.position==='owner'?'<form id="posLocation" class="form-stack"><label>External location ID<input name="location" required maxlength="180"></label><label>Branch ID<input name="branch_id" type="number" min="1" value="'+Number(shop.id)+'" required></label><button class="button">Сохранить branch mapping</button></form>':''}<h3>Sync history</h3>${h.items.map(r=>'<p>'+esc(r.mode)+' · '+esc(r.status)+' · '+esc(r.records_processed)+' обработано · '+esc(r.records_rejected)+' отклонено</p>').join('')||'<p>Синхронизация ещё не выполнялась.</p>'}<h3>Ошибки</h3>${e.items.map(r=>'<p>'+esc(r.code)+' · запись '+Number(r.record_index)+'</p>').join('')||'<p>Ошибок нет.</p>'}<h3>Product mappings</h3>${m.items.map(r=>'<article class="card"><p>'+esc(r.normalized_data?.name)+' · '+esc(r.status)+' · '+Number(r.confidence)+'%</p>'+ (shop.position==='owner'?'<form class="posMapping"><input name="master_product_id" type="number" min="1" required aria-label="Approved Global Product ID"><button class="button soft" data-mapping="'+Number(r.id)+'">Подтвердить Global Product ID</button></form>':'')+'</article>').join('')||'<p>Товаров пока нет.</p>'}`,'POS: настройка и история');
  const form=modal.querySelector('#posLocation');if(form)form.onsubmit=async event=>{event.preventDefault();try{const data=Object.fromEntries(new FormData(form));await api.request(base+'/'+id+'/locations/'+encodeURIComponent(data.location),{method:'PUT',body:{branch_id:Number(data.branch_id)}});toast('Филиал назначен');}catch(error){toast(error.message);}};
  modal.querySelectorAll('.posMapping').forEach(form=>form.onsubmit=async event=>{event.preventDefault();try{await api.request(base+'/'+id+'/mappings/'+Number(form.querySelector('button').dataset.mapping),{method:'PUT',body:{master_product_id:Number(new FormData(form).get('master_product_id'))}});toast('Mapping сохранён');modal.close();await refresh();}catch(error){toast(error.message);}});
 }));
}
